name: build

on:
  push:
    paths:
      - "src/**"
      - "test/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ConorMacBride/install-package@v1
        with:
          apt: gcc-11 g++-11 libreadline-dev libyaml-cpp-dev
          version: latest
          platform: x64
      - run: |
          pip install cogapp
      - run: |
          mkdir -p build
          cd build
          cmake -DBUILD_TESTS=OFF  ..
          make
        env:
          CC:   gcc-11
          CXX:  g++-11
