name: build

on:
    workflow_dispatch:
    push:
        paths:
            - "src/**"
            - "test/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: egor-tensin/setup-clang@v1
              with:
                  version: latest
                  platform: x64
            - run: |
                mkdir -p build
                cd build
                cmake  ..
                make
