name: test

on:
  push:
    paths:
      - "src/**"
      - "test/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/setup-clang@v1
      - uses: ConorMacBride/install-package@v1
        with:
          apt: valgrind libreadline-dev
          version: latest
          platform: x64
      - run: |
          mkdir -p build
          cd build
          cmake -DBUILD_JSD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug ..
          make
          make test
          env CTEST_OUTPUT_ON_FAILURE=1 make -d memcheck